// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa5RGzhQ5V4j-Jaan0TOz5EAOzVr8Uaaw',
    appId: '1:426036338767:web:cfc791a938842f1035ca3a',
    messagingSenderId: '426036338767',
    projectId: 'digitalridr-6ab34',
    authDomain: 'digitalridr-6ab34.firebaseapp.com',
    storageBucket: 'digitalridr-6ab34.firebasestorage.app',
    measurementId: 'G-EEB4V966ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcexdTJ6sSnVeO2RT4dw2_UMFhatDEskY',
    appId: '1:426036338767:android:641e1cda5e1884f035ca3a',
    messagingSenderId: '426036338767',
    projectId: 'digitalridr-6ab34',
    storageBucket: 'digitalridr-6ab34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmHfEKKkYCIg6x-CYD8wWYJtDGAQrGX-c',
    appId: '1:426036338767:ios:5c0c6b8f742a3d5a35ca3a',
    messagingSenderId: '426036338767',
    projectId: 'digitalridr-6ab34',
    storageBucket: 'digitalridr-6ab34.firebasestorage.app',
    iosClientId: '426036338767-flj8hld0td2ggneo551sln3scesg8srk.apps.googleusercontent.com',
    iosBundleId: 'com.mickoappservices.digital.ridr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmHfEKKkYCIg6x-CYD8wWYJtDGAQrGX-c',
    appId: '1:426036338767:ios:dbdccadd1d35e48235ca3a',
    messagingSenderId: '426036338767',
    projectId: 'digitalridr-6ab34',
    storageBucket: 'digitalridr-6ab34.firebasestorage.app',
    iosClientId: '426036338767-ogh45ufl6ifdpr5ej2chlj5nf67mqo2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalridr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa5RGzhQ5V4j-Jaan0TOz5EAOzVr8Uaaw',
    appId: '1:426036338767:web:dd7c7494317ea4fc35ca3a',
    messagingSenderId: '426036338767',
    projectId: 'digitalridr-6ab34',
    authDomain: 'digitalridr-6ab34.firebaseapp.com',
    storageBucket: 'digitalridr-6ab34.firebasestorage.app',
    measurementId: 'G-Y9HH62ME0E',
  );
}
