/// Flutter icons MyFlutterApp
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DigitalridrAppIcons {
  DigitalridrAppIcons._();

  static const _kFontFam = 'DigitalridrAppIcons';
  static const String? _kFontPkg = null;

  static const IconData laurel_wreath = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apartment_2 = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_filled = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_outlined = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chats = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apartment_1 = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
